version: "3.4"
services:
  tor-obfs4-bridge:
    image: zetneteork/tor-obfs4-bridge:0.4.8.16-1
    network_mode: bridge
    environment:
      # Exit with an error message if OR_PORT is unset or empty.
      - OR_PORT=${OR_PORT:?Env var OR_PORT is not set.}
      # Exit with an error message if PT_PORT is unset or empty.
      - PT_PORT=${PT_PORT:?Env var PT_PORT is not set.}
      # Exit with an error message if EMAIL is unset or empty.
      - EMAIL=${EMAIL:?Env var EMAIL is not set.}
      # Exit with an error message if TOR_OR_PORT_IPV4 is unset or empty.
      - TOR_OR_PORT_IPV4=${TOR_OR_PORT_IPV4:?Env var TOR_OR_PORT_IPV4 is not set.}
      # Exit with an error message if TOR_EXITRELAY is unset or empty.
      - TOR_EXITRELAY=${TOR_EXITRELAY:?Env var TOR_EXITRELAY is not set.}
      # Exit with an error message if TOR_BRIDGERELAY is unset or empty.
      - TOR_BRIDGERELAY=${TOR_BRIDGERELAY:?Env var TOR_BRIDGERELAY is not set.}
    volumes:
      - data:/var/lib/tor
    ports:
      - ${OR_PORT}:${OR_PORT}
      - ${PT_PORT}:${PT_PORT}
    restart: unless-stopped

volumes:
  data:
    name: tor-datadir-${OR_PORT}-${PT_PORT}
