apiVersion: v1
kind: Namespace
metadata:
  name: "tor"
  labels:
    name: "tornetworkproxy"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-pv-datadir
  namespace: tor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tor
  namespace: tor
  labels:
    apps: tor
spec:
  type: LoadBalancer
  ports:
    - port: 2123
      targetPort: 2123
      name: orport
      protocol: TCP
    - port: 2133
      targetPort: 2133
      name: ptport
      protocol: TCP
  selector:
    app: tor
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor
  namespace: tor
  labels:
    app: tor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      containers:
        - name: tor
          image: zetneteork/tor-obfs4-bridge:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Prague"
            - name: PT_PORT
              value: "2133"
            - name: EMAIL
              value: "tor@opentree.cz"
            - name: OR_PORT
              value: "2123"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          ports:
            -
              containerPort: 2123
              name: orport
              protocol: TCP
            -
              containerPort: 2133
              name: ptport
              protocol: TCP
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/tor
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: tor-pv-datadir
