apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-datadir
  namespace: tor
  labels:
    app.kubernetes.io/name: tor-obfs4-bridge
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
